pub mod array_permutation; // #479
pub mod at_most_distinct; // #485
pub mod construct_sentence; // #480
pub mod find_a_dup; // #476
pub mod find_celebrity; // #486
pub mod find_cousins; // #487
pub mod horizontal_distance; // #490
pub mod k_largest_in_bst; // #484
pub mod last_prisoner; // #483
pub mod longest_subarray; // #489
pub mod number_palindrome; // #491
pub mod range_sum_in_bst; // #482
pub mod simple_calculator; // #481
pub mod simple_queue; // #488
